// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class JavaDocsTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void JavaDocs() {
        // Test name: JavaDocs
        // Step # | name | target | value
        // 1 | open | /javase/9/docs/api/overview-summary.html |
        driver.get("https://docs.oracle.com/javase/9/docs/api/overview-summary.html");
        // 2 | setWindowSize | 1936x1056 |
        driver.manage().window().setSize(new Dimension(1936, 1056));
        // 3 | click | id=search |
        driver.findElement(By.id("search")).click();
        // 4 | type | id=search | java.lang.String
        driver.findElement(By.id("search")).sendKeys("java.lang.String");
        // 5 | click | xpath=//ul[@id='ui-id-1']/li[2] |
        driver.findElement(By.xpath("//ul[@id=\'ui-id-1\']/li[2]")).click();
        // 6 | click | css=.rowColor:nth-child(3) > .colConstructorName a |
        driver.findElement(By.cssSelector(".rowColor:nth-child(3) > .colConstructorName a")).click();
        // 7 | click | id=search |
        driver.findElement(By.id("search")).click();
        // 8 | type | id=search | javax.swing.JFrame
        driver.findElement(By.id("search")).sendKeys("javax.swing.JFrame");
        // 9 | click | xpath=//li[3]/a/span |
        driver.findElement(By.xpath("//li[3]/a/span")).click();
        // 10 | click | css=.altColor:nth-child(4) > .colConstructorName .memberNameLink > a |
        driver.findElement(By.cssSelector(".altColor:nth-child(4) > .colConstructorName .memberNameLink > a")).click();
    }
}
